### ISSUE TITLE
Class In2\\Femanager\\ViewHelpers\\Misc\\FormValidationDataViewHelper does not exist

### ISSUE THREAD

**Issue by mvnaz** [einpraegsam/femanagerextended#4]
Hello, everybody. I need your help. I installed femanagerextended. I can see new fields on back-end, but when I try to show new fields on back-end I have error. This is error which occurrence on log file.

Tue, 04 Apr 2017 16:47:58 +0300 [ALERT] request="082c6456d8296" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Code: 20170404164758970c9147 - {"exception":"ReflectionException: Class In2\\Femanager\\ViewHelpers\\Misc\\FormValidationDataViewHelper does not exist in \/Users\/workspace\/serve\/typo3-test\/typo3\/sysext\/extbase\/Classes\/Object\/Container\/ClassInfoFactory.php:35\nStack trace:\n#0 

I hope for your help. I tried everythink, and I can't find mistake myself.

**Comment by sbusemann** [comment]
this is outdated now - i will close it
