### ISSUE TITLE
Update for 8.7 and 9.x

### ISSUE THREAD

**Issue by ingeniumdesign** [einpraegsam/femanagerextended#9]
Hi, please update the Examples for the new TYPO3 8 and 9

Many Thanks!!!

**Comment by enem-frir** [comment]
Hello,

an update for TYPO3 10 would be awesome!

For now I get following error after submit the form:
_Exception while property mapping at property path "": Property "twitterId" was not found in target object of type "In2code\Femanager\Domain\Model\User"._

**Comment by ewokhias** [comment]
> Hello,
> 
> an update for TYPO3 10 would be awesome!
> 
> For now I get following error after submit the form:
> _Exception while property mapping at property path "": Property "twitterId" was not found in target object of type "In2code\Femanager\Domain\Model\User"._

I'm experiencing the same issue.

**Comment by bh-teufels** [comment]
same here 
how i fixed it:
-> Create own Extension from this and https://docs.typo3.org/p/in2code/femanager/6.1/en-us/Features/NewFields/Index.html

1. Create Configuration/Extbase/Persistence/Classes.php
```
<?php

declare(strict_types=1);

return [
    \MYEXT\MyExtFemanager\Domain\Model\User::class => [
        'tableName' => 'fe_users',
        'properties' => [
            'twitterId' => [
                'fieldName' => 'twitter_id'
            ],
            'skypeId' => [
                'fieldName' => 'skype_id'
            ],
        ],
    ],
];
```



2. Edit ext_localconf.php
```
<?php
if (!defined('TYPO3_MODE')) {
    die('Access denied.');
}

call_user_func(function () {
    // Register extended domain class
    \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\Object\Container\Container::class)
        ->registerImplementation(
            \In2code\Femanager\Domain\Model\User::class,
            \MYEXT\MyExtFemanager\Domain\Model\User::class
        );
});
```

**Comment by paddydrums** [comment]
> same here
> how i fixed it:
> -> Create own Extension from this and https://docs.typo3.org/p/in2code/femanager/6.1/en-us/Features/NewFields/Index.html
> 
> 1. Create Configuration/Extbase/Persistence/Classes.php
> 
> ```
> <?php
> 
> declare(strict_types=1);
> 
> return [
>     \MYEXT\MyExtFemanager\Domain\Model\User::class => [
>         'tableName' => 'fe_users',
>         'properties' => [
>             'twitterId' => [
>                 'fieldName' => 'twitter_id'
>             ],
>             'skypeId' => [
>                 'fieldName' => 'skype_id'
>             ],
>         ],
>     ],
> ];
> ```
> 
> 1. Edit ext_localconf.php
> 
> ```
> <?php
> if (!defined('TYPO3_MODE')) {
>     die('Access denied.');
> }
> 
> call_user_func(function () {
>     // Register extended domain class
>     \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\Object\Container\Container::class)
>         ->registerImplementation(
>             \In2code\Femanager\Domain\Model\User::class,
>             \MYEXT\MyExtFemanager\Domain\Model\User::class
>         );
> });
> ```

This did the trick for me, too!

**Comment by chrissander** [comment]
Another important change for V9 and 10 is that you habe to move the $tmpFeUsersColumns  Definition from etx_tables.php to the Configuration/TCA/Overrides/ Folder. Otherwise the new fields are only available while you are logged in as a backend user. This bug is very hard to find, as you test mostly while you are logged in

**Comment by GhanshyamBhava** [comment]
> same here how i fixed it: -> Create own Extension from this and https://docs.typo3.org/p/in2code/femanager/6.1/en-us/Features/NewFields/Index.html
> 
> 1. Create Configuration/Extbase/Persistence/Classes.php
> 
> ```
> <?php
> 
> declare(strict_types=1);
> 
> return [
>     \MYEXT\MyExtFemanager\Domain\Model\User::class => [
>         'tableName' => 'fe_users',
>         'properties' => [
>             'twitterId' => [
>                 'fieldName' => 'twitter_id'
>             ],
>             'skypeId' => [
>                 'fieldName' => 'skype_id'
>             ],
>         ],
>     ],
> ];
> ```
> 
> 2. Edit ext_localconf.php
> 
> ```
> <?php
> if (!defined('TYPO3_MODE')) {
>     die('Access denied.');
> }
> 
> call_user_func(function () {
>     // Register extended domain class
>     \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\Object\Container\Container::class)
>         ->registerImplementation(
>             \In2code\Femanager\Domain\Model\User::class,
>             \MYEXT\MyExtFemanager\Domain\Model\User::class
>         );
> });
> ```

This not working for my TYPO3 10.4, femanagaer 6.3.4 and PHP 7.4

**Comment by sbusemann** [comment]
it is included now for TYPO3 10
